**Lab - 8**<br>
**Name - Mohammed Abuzar Younus**<br>
**Student ID - 8903244**

Using PyTorch:<br>

Calculate the dot product between two vectors each of length 3 (1.5 points)<br>

In [23]:
# importing the require packages
import torch

In [24]:
# Define the vectors

#Method - 1
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

# Calculate the dot product using torch.dot()
dot_product = torch.dot(vector1, vector2)

print("Dot product:", dot_product.item())

Dot product: 32


In [25]:
# Define the vectors

#Method - 2

vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

# Calculate the dot product using element-wise multiplication and summation
dot_product = torch.sum(vector1 * vector2)

print("Dot product:", dot_product.item())

Dot product: 32


Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)<br>

In [26]:
# Define the matrices

#Method - 1

matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# Calculate the matrix multiplication using torch.matmul()
result = torch.matmul(matrix1, matrix2)

print("Matrix multiplication:")
print(result)

Matrix multiplication:
tensor([[19, 22],
        [43, 50]])


In [27]:
# Define the matrices

#Method - 2

matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# Calculate the matrix multiplication using the @ operator
result = matrix1 @ matrix2

print("Matrix multiplication:")
print(result)

Matrix multiplication:
tensor([[19, 22],
        [43, 50]])


Using Tensorflow:<br>

Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)<br>

In [28]:
# importing the require packages
import tensorflow as tf

In [29]:
# Define the vectors

#Method - 1

vector1 = tf.constant([1, 2, 3])
vector2 = tf.constant([4, 5, 6])

# Calculate the dot product using tf.tensordot()
dot_product = tf.tensordot(vector1, vector2, axes=1)

print("Dot product:", dot_product)


Dot product: tf.Tensor(32, shape=(), dtype=int32)


In [30]:
# Define the vectors

#Method - 2

vector1 = tf.constant([1, 2, 3])
vector2 = tf.constant([4, 5, 6])

# Calculate the dot product using element-wise multiplication and reduction
dot_product = tf.reduce_sum(vector1 * vector2)

print("Dot product:", dot_product)

Dot product: tf.Tensor(32, shape=(), dtype=int32)


Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)<br>

In [31]:
# Define the matrices

# method - 1

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Calculate the matrix multiplication using tf.matmul()
result = tf.matmul(matrix1, matrix2)

print("Matrix multiplication:")
print(result)

Matrix multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [32]:
# Define the matrices

# method - 2
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Calculate the matrix multiplication using the @ operator
result = matrix1 @ matrix2

print("Matrix multiplication:")
print(result)

Matrix multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
